services:
    database:
        build:
            context: .
            dockerfile: docker/database.dockerfile
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 3s
            retries: 3
    webapi:
        build:
            context: .
            dockerfile: docker/webapi.dockerfile
        ports:
            - "8080:8080"
        environment:
            - repositoryUrl=jdbc:postgresql://database:5432/
            - repositoryUsername=postgres
            - repositoryPassword=postgres
        depends_on:
            database:
                condition: service_healthy
